# This will add a comment to pull requests

name: Pull Request Commenter

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues.
            The 20 meter pacer test will begin in 30 seconds. Line up at the start.
            The running speed starts slowly, but gets faster each minute after you hear this signal.
            A single lap should be completed each time you hear this sound.
            Remember to run in a straight line, and run as long as possible.
            The second time you fail to complete a lap before the sound, your test is over.
            The test will begin on the word start.
            On your mark, get ready, start.
            !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

