# This workflow will create a Python virtual network, install requirements.txt
# and will run some unit tests

name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements.txt
        run: pip3 install -r requirements.txt
      - name: Run Pytests
        run: pytest
